version: "3.8"
services:
  app-db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '33066:3306'
    expose:
      - '3306'
    volumes:
      - ./data/db/mysql:/var/lib/mysql
